package inventory

import (
	"context"
	"strings"
	"time"

	"github.com/moby/moby/api/types/events"
	"github.com/moby/moby/client"
)

func (r *DockerReader) Start(ctx context.Context, notify func(Change)) {
	r.once.Do(func() {
		ctx, r.cancel = context.WithCancel(ctx)
		r.workers.Go(func() {
			for {
				r.collectMetrics(ctx)
				if ctx.Err() != nil {
					return
				}
				notify(Change{Metrics: true})
				select {
				case <-ctx.Done():
					return
				case <-time.After(5 * time.Second):
				}
			}
		})
		r.workers.Go(func() { r.watchEvents(ctx, notify) })
	})
}

func (r *DockerReader) watchEvents(ctx context.Context, notify func(Change)) {
	since := time.Now().UTC().Format(time.RFC3339Nano)
	retry := time.Second
	for ctx.Err() == nil {
		streamCtx, cancel := context.WithCancel(ctx)
		stream := r.client.Events(streamCtx, client.EventsListOptions{Since: since, Filters: client.Filters{"type": {"container": true}}})
		// Also reconcile after reconnect: Docker retains only a bounded event history.
		notify(Change{Inventory: true})
		connectedAt := time.Now()
	listening:
		for {
			select {
			case <-ctx.Done():
				cancel()
				return
			case <-stream.Err:
				break listening
			case event, ok := <-stream.Messages:
				if !ok {
					break listening
				}
				if event.TimeNano > 0 {
					since = time.Unix(0, event.TimeNano).UTC().Format(time.RFC3339Nano)
				}
				if r.handleEvent(event) {
					notify(Change{Inventory: true})
				}
			}
		}
		cancel()
		notify(Change{Inventory: true})
		if time.Since(connectedAt) > 10*time.Second {
			retry = time.Second
		}
		select {
		case <-ctx.Done():
			return
		case <-time.After(retry):
		}
		retry = min(retry*2, 30*time.Second)
	}
}

func (r *DockerReader) handleEvent(event events.Message) bool {
	if event.Type != events.ContainerEventType {
		return false
	}
	action := string(event.Action)
	if strings.HasPrefix(action, "health_status") {
		return true
	}
	switch action {
	case "create", "start", "stop", "die", "destroy", "restart", "kill", "oom", "pause", "unpause", "rename", "update":
	default:
		return false // Ignore exec/attach/log events generated by the UI itself.
	}
	if action == "start" || action == "stop" || action == "die" || action == "destroy" || action == "restart" {
		r.mu.Lock()
		r.generation++
		delete(r.metrics, event.Actor.ID)
		if action != "restart" {
			delete(r.started, event.Actor.ID)
		}
		delete(r.shells, event.Actor.ID)
		if action == "start" && event.TimeNano > 0 {
			if r.started == nil {
				r.started = make(map[string]time.Time)
			}
			r.started[event.Actor.ID] = time.Unix(0, event.TimeNano)
		}
		r.mu.Unlock()
	}
	return true
}
